### ISSUE TITLE
Menu text is not aligned

### ISSUE THREAD

**Issue by Aholicknight** [ruckage/es-theme-snes-mini#29]
I am using the latest version of the SNES Mini theme and for some reason the text in the games section is not centered. 

https://user-images.githubusercontent.com/7843719/160727421-9443395b-1963-4306-b9c2-68f87579f16b.mp4

This is the video of the problem, if anyone can help me or provide support, that would be great. Thank you!

**Comment by thias** [comment]
Duplicate of #22
